USE eTicketProject

CREATE TABLE Movie(
MovieID CHAR(4) NOT NULL PRIMARY KEY,
MovieName NVARCHAR(50) NOT NULL,
Genre NVARCHAR(50) NOT NULL,
MovieDuration INT NOT NULL,
MovieTime DATETIME NOT NULL,
);

CREATE TABLE Customer(
CustomerID CHAR(4) NOT NULL PRIMARY KEY,
CustomerName NVARCHAR(50) NOT NULL,
Email NVARCHAR(50) NOT NULL,
Pass NVARCHAR(50) NOT NULL
);

CREATE TABLE Theater(
TheaterID CHAR(4) NOT NULL PRIMARY KEY,
Capacity INT NOT NULL,
MovieID CHAR(4) NOT NULL FOREIGN KEY REFERENCES Movie(MovieID)
);

CREATE TABLE Seat(
SeatID CHAR(3) NOT NULL PRIMARY KEY,
TheaterID CHAR(4) NOT NULL FOREIGN KEY REFERENCES Theater(TheaterID),
CustomerID CHAR(4) NOT NULL FOREIGN KEY REFERENCES Customer(CustomerID)
);

CREATE TABLE TransactionDetail(
TransactionID CHAR(4) NOT NULL PRIMARY KEY,
TransactionDate DATETIME NOT NULL,
CustomerID CHAR(4) NOT NULL FOREIGN KEY REFERENCES Customer(CustomerID),
SeatID CHAR(3) NOT NULL FOREIGN KEY REFERENCES Seat(SeatID)
);